### ISSUE TITLE
linked bevy bug is fixed

### ISSUE THREAD

**Issue by phrohdoh** [guimcaballero/bevy_chess#2]
> Note: In theory this should work by just creating 4 materials and replacing the handles in the squares, but there's a bug in Bevy that makes that not work.

Links to https://github.com/bevyengine/bevy/issues/858 which has been resolved via https://github.com/bevyengine/bevy/pull/877 ([this comment](https://github.com/bevyengine/bevy/pull/877#issuecomment-729308434) confirms it).

**Comment by guimcaballero** [comment]
Thanks for the tip! I've reworked the tutorial to show a new version that uses this.
