### ISSUE TITLE
Movement broken after 1st capture

### ISSUE THREAD

**Issue by samcarey** [guimcaballero/bevy_chess#4]
After capturing a single pawn, pieces can no longer move. The sequence of moves shown in the readme GIF is no longer possible. 

This seems to have been triggered by the upgrade to Bevy 0.4 (324b6dcbcb5f4a3d18ea22df6b4d6b9db4faf970), as the commit just before (22f65da1bc602e817552d336a5d88bb45b4e317f) works fine.

Using Windows 10 64-bit.

**Comment by samcarey** [comment]
After the first capture, when I select a new piece, this line:

https://github.com/guimcaballero/bevy_chess/blob/6f72668f5377841d673f0a10921091b339d8c7b4/src/board.rs#L199

`get_mut` returns `Err(NoSuchEntity)`, whereas it usually returns something like `Ok((86v0, Piece { color: Black, piece_type: Pawn, x: 6, y: 3 }))`

**Comment by guimcaballero** [comment]
Thanks for the error report! 

It looks like the `SelectedPiece` resource wasn't being set correctly to None for some weird reason. Moving the resetting code to be inside the event fixed the issue.
