### ISSUE TITLE
Rust compilation error in tutorial

### ISSUE THREAD

**Issue by corintho** [guimcaballero/bevy_chess#6]
While follow the tutorial, when doing the "Implementing available squares" section I came across a compilation error.
```cannot borrow `pieces_query` as mutable more than once at a time```

This happens in the last code block in the section above. In there, it says to add the `pieces_vec` inside the `if let Ok` section, but you actually have to add it *before* that section.

**Comment by guimcaballero** [comment]
You're completely right, I've corrected it. Thanks for the report!
