### ISSUE TITLE
One more issue for Tutorial Code compilation

### ISSUE THREAD

**Issue by corintho** [guimcaballero/bevy_chess#7]
While following along, I had to do these updates to have the code working:
**Section:** Displaying the current turn
**code block**: first
**function**: `init_next_move_text`
**description**: When creating the `TextStyle`, it now takes another property: `alignment: TextAlignment`, I fixed mine by adding `..Default::default()` to the block

After this, I went until the end of the tutorial and it is all working nicely.

**Comment by guimcaballero** [comment]
It looks like a couple things slipped through the cracks on the upgrade to Bevy 0.4, so thanks for catching this! It's been corrected now.
